name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    container:
      image: ruby:${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@v2
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rake
